name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Descarga el repo
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Métricas clásicas
      - name: Generate Classic Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: 'local'
          committer_token: ""

      # 3. Gráfico contrib
      - name: Generate Isocalendar (Half-year)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          output_action: 'local'
          committer_token: ""
      
      # 4. Sube AMBOS archivos en un solo commit
      - name: Commit and push metrics
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.svg'
          message: '📊 Chore: Update metrics'
          author_name: 'GitHub Actions'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
